name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: marketdata_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Lint with flake8
        run: |
          flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Format with black
        run: black app/
      - name: Type check with mypy
        run: mypy app/ --ignore-missing-imports
      - name: Test with pytest
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/marketdata_test
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          PYTHONPATH: .
          TEST_DATABASE_URL: postgresql://postgres:password@localhost:5432/marketdata_test
        run: |
          pytest tests/ -v --cov=app --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t market-data-service:${{ github.sha }} .
      - name: Test Docker image
        run: |
          docker run -d --name test-container market-data-service:${{ github.sha }}
          sleep 5
          docker logs test-container
          docker stop test-container